# OMNIAUTH
FACEBOOK_APP_ID: "282523151767333"
FACEBOOK_SECRET: "cd8002901bdd85dedbb15944d91b803b"

TWITTER_API_KEY: "sGqABtLbkWDt0gItOqwFyw"
TWITTER_API_SECRET: "4TrM2Zs7ZDRSUomeMCL0zQwRzS2zKAYnibn1JAk"

GOOGLE_CLIENT_ID: "23605018266-prl8o4sj6n91mdokafjsr835vs7lffij.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "pVXjdvofI9e_CpuXRkZQQDar"