default: &default
  adapter: postgresql
  encoding: unicode
  username: mk
  password: kiwi123
  pool: 5
  #host: localhost
  #port: 5432

development:
  <<: *default
  database: raspas_development

test:
  <<: *default
  database: raspas_test
  
production:
  <<: *default
  database: raspas_production
  username: mk
  password: <%= ENV['RASPAS_DATABASE_PASSWORD'] %>